[package]
name = "ml_kem"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11.1"
arrayref = "0.3.9"
base64 = "0.22.1"
fips204 = "0.2.2"
generic-array = "1.1.0"
ml-kem = "0.2.1"
rand = "0.8.5"
rsa = "0.9.6"
